FROM ruby:3.1.2
ENV RAILS_ENV=development

RUN apt-get update && apt-get install -y \
    build-essential

RUN mkdir -p /app
WORKDIR /app

COPY Gemfile Gemfile.lock ./
RUN gem install bundler && bundle install --jobs=4 --retry=3

COPY . ./
RUN chmod +x ./scripts/install.sh
RUN ./scripts/install.sh

EXPOSE 3000
ENTRYPOINT ["./entrypoint.sh"]
CMD ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]
